from scrapy.item import Item, Field

class SportmanItem(Item):
    name = Field()
    short_desc = Field()
    description = Field()
    old_price = Field()
    custom_price = Field()
    product_id = Field()
    image_urls = Field()
    images = Field()
    normal_image_url = Field()
    color = Field()
    size = Field()
    recommended_product = Field()
    master_product_id = Field()
    color_value = Field()
    in_stock = Field()
    size_val = Field()
    color_options = Field()
    size_options = Field()
    viewstate1 = Field()
    viewstate2 = Field()
    viewstate3 = Field()
    viewstate4 = Field()
    viewstate5 = Field()
    viewstate6 = Field()
    eventval = Field()
    sku = Field()
    prevpage = Field()
    hidden = Field()